export const markets = [
  { label: "Andorra", code: "AD" },
  { label: "United Arab Emirates", code: "AE" },
  { label: "Antigua and Barbuda", code: "AG" },
  { label: "Albania", code: "AL" },
  { label: "Armenia", code: "AM" },
  { label: "Angola", code: "AO" },
  { label: "Argentina", code: "AR" },
  { label: "Austria", code: "AT" },
  { label: "Australia", code: "AU" },
  { label: "Azerbaijan", code: "AZ" },
  { label: "Bosnia and Herzegovina", code: "BA" },
  { label: "Barbados", code: "BB" },
  { label: "Bangladesh", code: "BD" },
  { label: "Belgium", code: "BE" },
  { label: "Burkina Faso", code: "BF" },
  { label: "Bulgaria", code: "BG" },
  { label: "Bahrain", code: "BH" },
  { label: "Burundi", code: "BI" },
  { label: "Benin", code: "BJ" },
  { label: "Brunei", code: "BN" },
  { label: "Bolivia", code: "BO" },
  { label: "Brazil", code: "BR" },
  { label: "Bahamas", code: "BS" },
  { label: "Bhutan", code: "BT" },
  { label: "Botswana", code: "BW" },
  { label: "Belarus", code: "BY" },
  { label: "Belize", code: "BZ" },
  { label: "Canada", code: "CA" },
  { label: "Democratic Republic of the Congo", code: "CD" },
  { label: "Republic of the Congo", code: "CG" },
  { label: "Switzerland", code: "CH" },
  { label: "Ivory Coast", code: "CI" },
  { label: "Chile", code: "CL" },
  { label: "Cameroon", code: "CM" },
  { label: "Colombia", code: "CO" },
  { label: "Costa Rica", code: "CR" },
  { label: "Cape Verde", code: "CV" },
  { label: "Curaçao", code: "CW" },
  { label: "Cyprus", code: "CY" },
  { label: "Czech Republic", code: "CZ" },
  { label: "Germany", code: "DE" },
  { label: "Djibouti", code: "DJ" },
  { label: "Denmark", code: "DK" },
  { label: "Dominica", code: "DM" },
  { label: "Dominican Republic", code: "DO" },
  { label: "Algeria", code: "DZ" },
  { label: "Ecuador", code: "EC" },
  { label: "Estonia", code: "EE" },
  { label: "Egypt", code: "EG" },
  { label: "Spain", code: "ES" },
  { label: "Ethiopia", code: "ET" },
  { label: "Finland", code: "FI" },
  { label: "Fiji", code: "FJ" },
  { label: "Micronesia", code: "FM" },
  { label: "France", code: "FR" },
  { label: "Gabon", code: "GA" },
  { label: "United Kingdom", code: "GB" },
  { label: "Grenada", code: "GD" },
  { label: "Georgia", code: "GE" },
  { label: "Ghana", code: "GH" },
  { label: "Gambia", code: "GM" },
  { label: "Guinea", code: "GN" },
  { label: "Equatorial Guinea", code: "GQ" },
  { label: "Greece", code: "GR" },
  { label: "Guatemala", code: "GT" },
  { label: "Guinea-Bissau", code: "GW" },
  { label: "Guyana", code: "GY" },
  { label: "Hong Kong", code: "HK" },
  { label: "Honduras", code: "HN" },
  { label: "Croatia", code: "HR" },
  { label: "Haiti", code: "HT" },
  { label: "Hungary", code: "HU" },
  { label: "Indonesia", code: "ID" },
  { label: "Ireland", code: "IE" },
  { label: "Israel", code: "IL" },
  { label: "India", code: "IN" },
  { label: "Iraq", code: "IQ" },
  { label: "Iceland", code: "IS" },
  { label: "Italy", code: "IT" },
  { label: "Jamaica", code: "JM" },
  { label: "Jordan", code: "JO" },
  { label: "Japan", code: "JP" },
  { label: "Kenya", code: "KE" },
  { label: "Kyrgyzstan", code: "KG" },
  { label: "Cambodia", code: "KH" },
  { label: "Kiribati", code: "KI" },
  { label: "Comoros", code: "KM" },
  { label: "Saint Kitts and Nevis", code: "KN" },
  { label: "South Korea", code: "KR" },
  { label: "Kuwait", code: "KW" },
  { label: "Kazakhstan", code: "KZ" },
  { label: "Laos", code: "LA" },
  { label: "Lebanon", code: "LB" },
  { label: "Saint Lucia", code: "LC" },
  { label: "Liechtenstein", code: "LI" },
  { label: "Sri Lanka", code: "LK" },
  { label: "Liberia", code: "LR" },
  { label: "Lesotho", code: "LS" },
  { label: "Lithuania", code: "LT" },
  { label: "Luxembourg", code: "LU" },
  { label: "Latvia", code: "LV" },
  { label: "Libya", code: "LY" },
  { label: "Morocco", code: "MA" },
  { label: "Monaco", code: "MC" },
  { label: "Moldova", code: "MD" },
  { label: "Montenegro", code: "ME" },
  { label: "Madagascar", code: "MG" },
  { label: "Marshall Islands", code: "MH" },
  { label: "North Macedonia", code: "MK" },
  { label: "Mali", code: "ML" },
  { label: "Mongolia", code: "MN" },
  { label: "Macau", code: "MO" },
  { label: "Mauritania", code: "MR" },
  { label: "Malta", code: "MT" },
  { label: "Mauritius", code: "MU" },
  { label: "Maldives", code: "MV" },
  { label: "Malawi", code: "MW" },
  { label: "Mexico", code: "MX" },
  { label: "Malaysia", code: "MY" },
  { label: "Mozambique", code: "MZ" },
  { label: "Namibia", code: "NA" },
  { label: "Niger", code: "NE" },
  { label: "Nigeria", code: "NG" },
  { label: "Nicaragua", code: "NI" },
  { label: "Netherlands", code: "NL" },
  { label: "Norway", code: "NO" },
  { label: "Nepal", code: "NP" },
  { label: "Nauru", code: "NR" },
  { label: "New Zealand", code: "NZ" },
  { label: "Oman", code: "OM" },
  { label: "Panama", code: "PA" },
  { label: "Peru", code: "PE" },
  { label: "Papua New Guinea", code: "PG" },
  { label: "Philippines", code: "PH" },
  { label: "Pakistan", code: "PK" },
  { label: "Poland", code: "PL" },
  { label: "Palestine", code: "PS" },
  { label: "Portugal", code: "PT" },
  { label: "Palau", code: "PW" },
  { label: "Paraguay", code: "PY" },
  { label: "Qatar", code: "QA" },
  { label: "Romania", code: "RO" },
  { label: "Serbia", code: "RS" },
  { label: "Rwanda", code: "RW" },
  { label: "Saudi Arabia", code: "SA" },
  { label: "Solomon Islands", code: "SB" },
  { label: "Seychelles", code: "SC" },
  { label: "Sweden", code: "SE" },
  { label: "Singapore", code: "SG" },
  { label: "Slovenia", code: "SI" },
  { label: "Slovakia", code: "SK" },
  { label: "Sierra Leone", code: "SL" },
  { label: "San Marino", code: "SM" },
  { label: "Senegal", code: "SN" },
  { label: "Suriname", code: "SR" },
  { label: "São Tomé and Príncipe", code: "ST" },
  { label: "El Salvador", code: "SV" },
  { label: "Eswatini", code: "SZ" },
  { label: "Chad", code: "TD" },
  { label: "Togo", code: "TG" },
  { label: "Thailand", code: "TH" },
  { label: "Tajikistan", code: "TJ" },
  { label: "Timor-Leste", code: "TL" },
  { label: "Tunisia", code: "TN" },
  { label: "Tonga", code: "TO" },
  { label: "Turkey", code: "TR" },
  { label: "Trinidad and Tobago", code: "TT" },
  { label: "Tuvalu", code: "TV" },
  { label: "Taiwan", code: "TW" },
  { label: "Tanzania", code: "TZ" },
  { label: "Ukraine", code: "UA" },
  { label: "Uganda", code: "UG" },
  { label: "United States", code: "US" },
  { label: "Uruguay", code: "UY" },
  { label: "Uzbekistan", code: "UZ" },
  { label: "Saint Vincent and the Grenadines", code: "VC" },
  { label: "Venezuela", code: "VE" },
  { label: "Vietnam", code: "VN" },
  { label: "Vanuatu", code: "VU" },
  { label: "Samoa", code: "WS" },
  { label: "Kosovo", code: "XK" },
  { label: "South Africa", code: "ZA" },
  { label: "Zambia", code: "ZM" },
  { label: "Zimbabwe", code: "ZW" },
];
